//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Article_type
{
    public Article_type()
    {
        this.Contractor_Order = new HashSet<Contractor_Order>();
    }

    public int Id { get; set; }
    public string Name { get; set; }

    public virtual ICollection<Contractor_Order> Contractor_Order { get; set; }
}

public partial class Change_Request
{
    public int Id { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int UserId { get; set; }

    public virtual User User { get; set; }
}

public partial class CMM_Program
{
    public CMM_Program()
    {
        this.CMM_Program_Index = new HashSet<CMM_Program_Index>();
        this.Technology_Stage = new HashSet<Technology_Stage>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int UserId { get; set; }
    public Nullable<int> FixtureId { get; set; }
    public int CNC_MachineId { get; set; }
    public Nullable<int> Setup_SheetId { get; set; }

    public virtual ICollection<CMM_Program_Index> CMM_Program_Index { get; set; }
    public virtual User User { get; set; }
    public virtual Fixture Fixture { get; set; }
    public virtual CNC_Machine CNC_Machine { get; set; }
    public virtual ICollection<Technology_Stage> Technology_Stage { get; set; }
    public virtual Setup_Sheet Setup_Sheet { get; set; }
}

public partial class CMM_Program_Files
{
    public int Id { get; set; }
    public string File_title { get; set; }
    public string File_name_number { get; set; }
    public string filePath { get; set; }
    public string File_extension { get; set; }
    public Nullable<decimal> File_size { get; set; }
    public string Description { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int CMM_Program_IndexId { get; set; }
    public int UserId { get; set; }

    public virtual CMM_Program_Index CMM_Program_Index { get; set; }
    public virtual User User { get; set; }
}

public partial class CMM_Program_Index
{
    public CMM_Program_Index()
    {
        this.CMM_Program_Files = new HashSet<CMM_Program_Files>();
    }

    public int Id { get; set; }
    public int Index_number { get; set; }
    public string Index_description { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public System.DateTime Date_approved { get; set; }
    public int CMM_ProgramId { get; set; }
    public int CMM_StatusId { get; set; }
    public int UserId { get; set; }
    public int UserId_approved { get; set; }

    public virtual CMM_Program CMM_Program { get; set; }
    public virtual CMM_Status CMM_Status { get; set; }
    public virtual ICollection<CMM_Program_Files> CMM_Program_Files { get; set; }
    public virtual User User { get; set; }
    public virtual User User_approved { get; set; }
}

public partial class CMM_Status
{
    public CMM_Status()
    {
        this.CMM_Program_Index = new HashSet<CMM_Program_Index>();
    }

    public int Id { get; set; }
    public string Name { get; set; }

    public virtual ICollection<CMM_Program_Index> CMM_Program_Index { get; set; }
}

public partial class CNC_Machine
{
    public CNC_Machine()
    {
        this.CNC_Program = new HashSet<CNC_Program>();
        this.CNC_Machine_Files = new HashSet<CNC_Machine_Files>();
        this.CMM_Program = new HashSet<CMM_Program>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string Manufacturer { get; set; }
    public string Serial_number { get; set; }
    public string Model { get; set; }
    public Nullable<short> Moc { get; set; }
    public string Control { get; set; }
    public Nullable<short> Axis { get; set; }
    public System.DateTime Date_purchased { get; set; }
    public Nullable<short> Max_spindle { get; set; }
    public int CNC_Machine_TypeId { get; set; }
    public string Description { get; set; }
    public int Tool_Holder_SystemId { get; set; }

    public virtual ICollection<CNC_Program> CNC_Program { get; set; }
    public virtual ICollection<CNC_Machine_Files> CNC_Machine_Files { get; set; }
    public virtual CNC_Machine_Type CNC_Machine_Type { get; set; }
    public virtual ICollection<CMM_Program> CMM_Program { get; set; }
    public virtual Tool_Holder_System Tool_Holder_System { get; set; }
}

public partial class CNC_Machine_Files
{
    public int Id { get; set; }
    public string File_title { get; set; }
    public string File_name_number { get; set; }
    public string filePath { get; set; }
    public string File_extension { get; set; }
    public Nullable<decimal> File_size { get; set; }
    public string Description { get; set; }
    public int CNC_MachineId { get; set; }

    public virtual CNC_Machine CNC_Machine { get; set; }
}

public partial class CNC_Machine_Type
{
    public CNC_Machine_Type()
    {
        this.CNC_Machine = new HashSet<CNC_Machine>();
    }

    public int Id { get; set; }
    public string Name { get; set; }

    public virtual ICollection<CNC_Machine> CNC_Machine { get; set; }
}

public partial class CNC_Program
{
    public CNC_Program()
    {
        this.CNC_Program_Index = new HashSet<CNC_Program_Index>();
        this.CNC_Subprogram = new HashSet<CNC_Subprogram>();
        this.Technology_Stage = new HashSet<Technology_Stage>();
        this.ToolCNC_Program = new HashSet<ToolCNC_Program>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int UserId { get; set; }
    public int CNC_MachineId { get; set; }
    public Nullable<int> FixtureId { get; set; }
    public Nullable<int> Setup_SheetId { get; set; }

    public virtual ICollection<CNC_Program_Index> CNC_Program_Index { get; set; }
    public virtual User User { get; set; }
    public virtual CNC_Machine CNC_Machine { get; set; }
    public virtual ICollection<CNC_Subprogram> CNC_Subprogram { get; set; }
    public virtual Fixture Fixture { get; set; }
    public virtual ICollection<Technology_Stage> Technology_Stage { get; set; }
    public virtual ICollection<ToolCNC_Program> ToolCNC_Program { get; set; }
    public virtual Setup_Sheet Setup_Sheet { get; set; }
}

public partial class CNC_Program_Files
{
    public int Id { get; set; }
    public string File_title { get; set; }
    public string File_name_number { get; set; }
    public string filePath { get; set; }
    public string File_extension { get; set; }
    public Nullable<decimal> File_size { get; set; }
    public string Description { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int CNC_Program_IndexId { get; set; }
    public int UserId { get; set; }

    public virtual CNC_Program_Index CNC_Program_Index { get; set; }
    public virtual User User { get; set; }
}

public partial class CNC_Program_Index
{
    public CNC_Program_Index()
    {
        this.CNC_Program_Files = new HashSet<CNC_Program_Files>();
    }

    public int Id { get; set; }
    public int Index_number { get; set; }
    public string Index_description { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int UserId { get; set; }
    public int CNC_ProgramId { get; set; }
    public System.DateTime Date_approved { get; set; }
    public int UserId_approved { get; set; }
    public int CNC_StatusId { get; set; }

    public virtual User User { get; set; }
    public virtual CNC_Program CNC_Program { get; set; }
    public virtual ICollection<CNC_Program_Files> CNC_Program_Files { get; set; }
    public virtual User User_approved { get; set; }
    public virtual CNC_Status CNC_Status { get; set; }
}

public partial class CNC_Status
{
    public CNC_Status()
    {
        this.CNC_Program_Index = new HashSet<CNC_Program_Index>();
        this.CNC_Subprogram_Index = new HashSet<CNC_Subprogram_Index>();
    }

    public int Id { get; set; }
    public string Name { get; set; }

    public virtual ICollection<CNC_Program_Index> CNC_Program_Index { get; set; }
    public virtual ICollection<CNC_Subprogram_Index> CNC_Subprogram_Index { get; set; }
}

public partial class CNC_Subprogram
{
    public CNC_Subprogram()
    {
        this.CNC_Subprogram_Index = new HashSet<CNC_Subprogram_Index>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int UserId { get; set; }
    public int CNC_ProgramId { get; set; }

    public virtual ICollection<CNC_Subprogram_Index> CNC_Subprogram_Index { get; set; }
    public virtual User User { get; set; }
    public virtual CNC_Program CNC_Program { get; set; }
}

public partial class CNC_Subprogram_Files
{
    public int Id { get; set; }
    public string File_title { get; set; }
    public string File_name_number { get; set; }
    public string filePath { get; set; }
    public string File_extension { get; set; }
    public Nullable<decimal> File_size { get; set; }
    public string Description { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int CNC_Subprogram_IndexId { get; set; }
    public int UserId { get; set; }

    public virtual CNC_Subprogram_Index CNC_Subprogram_Index { get; set; }
    public virtual User User { get; set; }
}

public partial class CNC_Subprogram_Index
{
    public CNC_Subprogram_Index()
    {
        this.CNC_Subprogram_Files = new HashSet<CNC_Subprogram_Files>();
    }

    public int Id { get; set; }
    public int Index_number { get; set; }
    public string Index_description { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int CNC_SubprogramId { get; set; }
    public int UserId { get; set; }
    public int CNC_StatusId { get; set; }
    public System.DateTime Date_approved { get; set; }
    public int UserId_approved { get; set; }

    public virtual CNC_Subprogram CNC_Subprogram { get; set; }
    public virtual User User { get; set; }
    public virtual ICollection<CNC_Subprogram_Files> CNC_Subprogram_Files { get; set; }
    public virtual CNC_Status CNC_Status { get; set; }
    public virtual User User_approved { get; set; }
}

public partial class Comment
{
    public int Id { get; set; }
    public string Description { get; set; }
    public System.DateTime Date_created { get; set; }
    public int UserId { get; set; }
    public Nullable<int> CustomerId { get; set; }
    public Nullable<int> Customer_ContactId { get; set; }
    public Nullable<int> ContractorId { get; set; }
    public Nullable<int> Contractor_ContactId { get; set; }
    public Nullable<int> Contractor_OrderId { get; set; }
    public Nullable<int> Customer_OrderId { get; set; }
    public Nullable<int> Customer_ProductId { get; set; }
    public Nullable<int> Customer_PartId { get; set; }
    public Nullable<int> Customer_Part_IndexId { get; set; }
    public Nullable<int> Customer_Product_IndexId { get; set; }
    public Nullable<int> Customer_FilesId { get; set; }
    public Nullable<int> TaskId { get; set; }
    public Nullable<int> NotificationId { get; set; }

    public virtual User User { get; set; }
    public virtual Customer Customer { get; set; }
    public virtual Customer_Contact Customer_Contact { get; set; }
    public virtual Contractor Contractor { get; set; }
    public virtual Contractor_Contact Contractor_Contact { get; set; }
    public virtual Contractor_Order Contractor_Order { get; set; }
    public virtual Customer_Order Customer_Order { get; set; }
    public virtual Customer_Product Customer_Product { get; set; }
    public virtual Customer_Part Customer_Part { get; set; }
    public virtual Customer_Part_Index Customer_Part_Index { get; set; }
    public virtual Customer_Product_Index Customer_Product_Index { get; set; }
    public virtual Customer_Files Customer_Files { get; set; }
    public virtual Task Task { get; set; }
    public virtual Notification Notification { get; set; }
}

public partial class Contractor
{
    public Contractor()
    {
        this.Contractor_Contact = new HashSet<Contractor_Contact>();
        this.Contractor_Order = new HashSet<Contractor_Order>();
        this.Comments = new HashSet<Comment>();
        this.Fixture = new HashSet<Fixture>();
        this.Tool_Element = new HashSet<Tool_Element>();
        this.Production_material = new HashSet<Production_material>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string Address { get; set; }
    public string City { get; set; }
    public string Postal_Code { get; set; }
    public string Phone { get; set; }
    public string Email { get; set; }
    public string Www { get; set; }
    public string Description { get; set; }
    public int Contractor_categoryId { get; set; }
    public int CountryId { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int UserId { get; set; }

    public virtual ICollection<Contractor_Contact> Contractor_Contact { get; set; }
    public virtual ICollection<Contractor_Order> Contractor_Order { get; set; }
    public virtual Contractor_category Contractor_category { get; set; }
    public virtual Country Country { get; set; }
    public virtual ICollection<Comment> Comments { get; set; }
    public virtual User User { get; set; }
    public virtual ICollection<Fixture> Fixture { get; set; }
    public virtual ICollection<Tool_Element> Tool_Element { get; set; }
    public virtual ICollection<Production_material> Production_material { get; set; }
}

public partial class Contractor_category
{
    public Contractor_category()
    {
        this.Contractor = new HashSet<Contractor>();
    }

    public int Id { get; set; }
    public string Nazwa { get; set; }

    public virtual ICollection<Contractor> Contractor { get; set; }
}

public partial class Contractor_Contact
{
    public Contractor_Contact()
    {
        this.Comments = new HashSet<Comment>();
    }

    public int Id { get; set; }
    public string F_Name { get; set; }
    public string L_Name { get; set; }
    public string W_Phone_No { get; set; }
    public string M_Phone_No { get; set; }
    public string Email { get; set; }
    public string Department { get; set; }
    public int ContractorId { get; set; }
    public string Description { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int UserId { get; set; }
    public string Position { get; set; }

    public virtual Contractor Contractor { get; set; }
    public virtual ICollection<Comment> Comments { get; set; }
    public virtual User User { get; set; }
}

public partial class Contractor_Order
{
    public Contractor_Order()
    {
        this.Comments = new HashSet<Comment>();
        this.Fixture = new HashSet<Fixture>();
        this.Score = new HashSet<Score>();
    }

    public int Id { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public System.DateTime Date_required { get; set; }
    public Nullable<System.DateTime> Date_delivered { get; set; }
    public int ContractorId { get; set; }
    public double Total_price { get; set; }
    public int UserId { get; set; }
    public string Contractor_offer_name_number { get; set; }
    public int Article_typeId { get; set; }
    public int Order_StatusId { get; set; }

    public virtual Contractor Contractor { get; set; }
    public virtual ICollection<Comment> Comments { get; set; }
    public virtual User User { get; set; }
    public virtual ICollection<Fixture> Fixture { get; set; }
    public virtual Article_type Article_type { get; set; }
    public virtual ICollection<Score> Score { get; set; }
    public virtual Order_Status Order_Status { get; set; }
}

public partial class Country
{
    public Country()
    {
        this.Customers = new HashSet<Customer>();
        this.Contractors = new HashSet<Contractor>();
    }

    public int Id { get; set; }
    public string Name { get; set; }

    public virtual ICollection<Customer> Customers { get; set; }
    public virtual ICollection<Contractor> Contractors { get; set; }
}

public partial class Customer
{
    public Customer()
    {
        this.Customer_Contacts = new HashSet<Customer_Contact>();
        this.Customer_Products = new HashSet<Customer_Product>();
        this.Customer_Parts = new HashSet<Customer_Part>();
        this.Comments = new HashSet<Comment>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string Address { get; set; }
    public string City { get; set; }
    public string Postal_Code { get; set; }
    public string Phone { get; set; }
    public string Email { get; set; }
    public string Www { get; set; }
    public int CountryId { get; set; }
    public string Description { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int UserId { get; set; }

    public virtual ICollection<Customer_Contact> Customer_Contacts { get; set; }
    public virtual ICollection<Customer_Product> Customer_Products { get; set; }
    public virtual ICollection<Customer_Part> Customer_Parts { get; set; }
    public virtual Country Country1 { get; set; }
    public virtual User User { get; set; }
    public virtual ICollection<Comment> Comments { get; set; }
}

public partial class Customer_Contact
{
    public Customer_Contact()
    {
        this.Comments = new HashSet<Comment>();
        this.Customer_Parts_sales = new HashSet<Customer_Part>();
        this.Customer_Part_technology = new HashSet<Customer_Part>();
        this.Customer_Part_quality = new HashSet<Customer_Part>();
        this.Customer_Product = new HashSet<Customer_Product>();
        this.Customer_Product1 = new HashSet<Customer_Product>();
        this.Customer_Product2 = new HashSet<Customer_Product>();
    }

    public int Id { get; set; }
    public string F_Name { get; set; }
    public string L_Name { get; set; }
    public string Position { get; set; }
    public string W_Phone_No { get; set; }
    public string M_Phone_No { get; set; }
    public string Email { get; set; }
    public string Department { get; set; }
    public int CustomerId { get; set; }
    public string Description { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int UserId { get; set; }

    public virtual Customer Customer { get; set; }
    public virtual User User { get; set; }
    public virtual ICollection<Comment> Comments { get; set; }
    public virtual ICollection<Customer_Part> Customer_Parts_sales { get; set; }
    public virtual ICollection<Customer_Part> Customer_Part_technology { get; set; }
    public virtual ICollection<Customer_Part> Customer_Part_quality { get; set; }
    public virtual ICollection<Customer_Product> Customer_Product { get; set; }
    public virtual ICollection<Customer_Product> Customer_Product1 { get; set; }
    public virtual ICollection<Customer_Product> Customer_Product2 { get; set; }
}

public partial class Customer_Files
{
    public Customer_Files()
    {
        this.Comments = new HashSet<Comment>();
    }

    public int Id { get; set; }
    public string File_title { get; set; }
    public string File_name_number { get; set; }
    public short Typ { get; set; }
    public Nullable<int> Customer_Part_IndexId { get; set; }
    public Nullable<int> Customer_Product_IndexId { get; set; }
    public Nullable<int> Customer_OrderId { get; set; }
    public string filePath { get; set; }
    public string File_extension { get; set; }
    public Nullable<decimal> File_size { get; set; }
    public string Description { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int UserId { get; set; }

    public virtual Customer_Part_Index Customer_Part_Index { get; set; }
    public virtual Customer_Product_Index Customer_Product_Index { get; set; }
    public virtual Customer_Order Customer_Order { get; set; }
    public virtual User User { get; set; }
    public virtual ICollection<Comment> Comments { get; set; }
}

public partial class Customer_Order
{
    public Customer_Order()
    {
        this.Production_Orders = new HashSet<Production_Order>();
        this.Customer_Files = new HashSet<Customer_Files>();
        this.Comments = new HashSet<Comment>();
    }

    public int Id { get; set; }
    public string Number { get; set; }
    public System.DateTime Date { get; set; }
    public string Quantity { get; set; }
    public System.DateTime Date_required { get; set; }

    public virtual ICollection<Production_Order> Production_Orders { get; set; }
    public virtual ICollection<Customer_Files> Customer_Files { get; set; }
    public virtual ICollection<Comment> Comments { get; set; }
}

public partial class Customer_Part
{
    public Customer_Part()
    {
        this.Notifications = new HashSet<Notification>();
        this.Customer_Part_Index = new HashSet<Customer_Part_Index>();
        this.Comments = new HashSet<Comment>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string Number { get; set; }
    public string Description { get; set; }
    public int CustomerId { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int UserId { get; set; }

    public virtual Customer Customer { get; set; }
    public virtual ICollection<Notification> Notifications { get; set; }
    public virtual ICollection<Customer_Part_Index> Customer_Part_Index { get; set; }
    public virtual User User { get; set; }
    public virtual Customer_Contact Customer_Contact_sales { get; set; }
    public virtual Customer_Contact Customer_Contact_technology { get; set; }
    public virtual Customer_Contact Customer_Contact_quality { get; set; }
    public virtual ICollection<Comment> Comments { get; set; }
}

public partial class Customer_Part_Index
{
    public Customer_Part_Index()
    {
        this.Customer_Files = new HashSet<Customer_Files>();
        this.Comments = new HashSet<Comment>();
        this.Technology = new HashSet<Technology>();
    }

    public int Id { get; set; }
    public string Index_number { get; set; }
    public string Index_description { get; set; }
    public string Index_designer { get; set; }
    public System.DateTime Index_date { get; set; }
    public int Customer_PartId { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int UserId { get; set; }
    public System.DateTime Date_received { get; set; }
    public Nullable<int> Customer_Product_IndexId { get; set; }

    public virtual Customer_Part Customer_Part { get; set; }
    public virtual ICollection<Customer_Files> Customer_Files { get; set; }
    public virtual User User { get; set; }
    public virtual ICollection<Comment> Comments { get; set; }
    public virtual Customer_Product_Index Customer_Product_Index { get; set; }
    public virtual ICollection<Technology> Technology { get; set; }
}

public partial class Customer_Product
{
    public Customer_Product()
    {
        this.Notifications = new HashSet<Notification>();
        this.Customer_Index = new HashSet<Customer_Product_Index>();
        this.Comments = new HashSet<Comment>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string Number { get; set; }
    public string Description { get; set; }
    public int CustomerId { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int UserId { get; set; }

    public virtual Customer Customer { get; set; }
    public virtual ICollection<Notification> Notifications { get; set; }
    public virtual ICollection<Customer_Product_Index> Customer_Index { get; set; }
    public virtual User User { get; set; }
    public virtual Customer_Contact Customer_Contact_sales { get; set; }
    public virtual Customer_Contact Customer_Contact_technology { get; set; }
    public virtual Customer_Contact Customer_Contact_quality { get; set; }
    public virtual ICollection<Comment> Comments { get; set; }
}

public partial class Customer_Product_Index
{
    public Customer_Product_Index()
    {
        this.Customer_Files = new HashSet<Customer_Files>();
        this.Comments = new HashSet<Comment>();
        this.Customer_Part_Index = new HashSet<Customer_Part_Index>();
    }

    public int Id { get; set; }
    public string Index_number { get; set; }
    public string Index_description { get; set; }
    public string Index_designer { get; set; }
    public System.DateTime Index_date { get; set; }
    public Nullable<int> Customer_ProductId { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int UserId { get; set; }
    public System.DateTime Date_received { get; set; }

    public virtual Customer_Product Customer_Product { get; set; }
    public virtual ICollection<Customer_Files> Customer_Files { get; set; }
    public virtual User User { get; set; }
    public virtual ICollection<Comment> Comments { get; set; }
    public virtual ICollection<Customer_Part_Index> Customer_Part_Index { get; set; }
}

public partial class Department
{
    public Department()
    {
        this.Users = new HashSet<User>();
    }

    public int Id { get; set; }
    public string Name { get; set; }

    public virtual ICollection<User> Users { get; set; }
}

public partial class DocumentInOut
{
    public int Id { get; set; }
    public string Date_out { get; set; }
    public string Date_in { get; set; }
    public int UserId { get; set; }
    public int UserId1 { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public string Description { get; set; }

    public virtual User User_received { get; set; }
    public virtual User User { get; set; }
}

public partial class Fixture
{
    public Fixture()
    {
        this.Fixture_Document_File = new HashSet<Fixture_Document_File>();
        this.CNC_Program = new HashSet<CNC_Program>();
        this.CMM_Program = new HashSet<CMM_Program>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public int ContractorId { get; set; }
    public Nullable<int> Contractor_OrderId { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int UserId { get; set; }

    public virtual User User { get; set; }
    public virtual Contractor_Order Contractor_Order { get; set; }
    public virtual Contractor Contractor { get; set; }
    public virtual ICollection<Fixture_Document_File> Fixture_Document_File { get; set; }
    public virtual ICollection<CNC_Program> CNC_Program { get; set; }
    public virtual ICollection<CMM_Program> CMM_Program { get; set; }
}

public partial class Fixture_Document_File
{
    public int Id { get; set; }
    public string File_title { get; set; }
    public int Index { get; set; }
    public int Fixture_Document_TypeId { get; set; }
    public string Description { get; set; }
    public string filePath { get; set; }
    public string File_extension { get; set; }
    public Nullable<long> File_size { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public Nullable<int> FixtureId { get; set; }

    public virtual Fixture_Document_Type Fixture_Document_Type { get; set; }
    public virtual Fixture Fixture { get; set; }
}

public partial class Fixture_Document_Type
{
    public Fixture_Document_Type()
    {
        this.Fixture_Document_File = new HashSet<Fixture_Document_File>();
    }

    public int Id { get; set; }
    public string Name { get; set; }

    public virtual ICollection<Fixture_Document_File> Fixture_Document_File { get; set; }
}

public partial class FormTemplate_Files
{
    public int Id { get; set; }
    public string Title { get; set; }
    public short Index { get; set; }
    public string filePath { get; set; }
    public string File_extension { get; set; }
    public Nullable<decimal> File_size { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int FormTemplatesId { get; set; }

    public virtual FormTemplates FormTemplates { get; set; }
}

public partial class FormTemplates
{
    public FormTemplates()
    {
        this.FormTemplate_Files = new HashSet<FormTemplate_Files>();
    }

    public int Id { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int FormTypeId { get; set; }

    public virtual FormType FormType { get; set; }
    public virtual ICollection<FormTemplate_Files> FormTemplate_Files { get; set; }
}

public partial class FormType
{
    public FormType()
    {
        this.FormTemplates = new HashSet<FormTemplates>();
    }

    public int Id { get; set; }
    public string Name { get; set; }

    public virtual ICollection<FormTemplates> FormTemplates { get; set; }
}

public partial class Notification
{
    public Notification()
    {
        this.Task = new HashSet<Task>();
        this.Comment = new HashSet<Comment>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public Nullable<int> Customer_PartId { get; set; }
    public Nullable<int> Customer_ProductId { get; set; }
    public System.DateTime RequiredEndDate { get; set; }
    public Nullable<System.DateTime> EndDate { get; set; }
    public int UserId { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int NotificationStatusId { get; set; }
    public int NotyficationTypeId { get; set; }

    public virtual User User { get; set; }
    public virtual Customer_Part Customer_Part { get; set; }
    public virtual Customer_Product Customer_Product { get; set; }
    public virtual ICollection<Task> Task { get; set; }
    public virtual ICollection<Comment> Comment { get; set; }
    public virtual NotificationStatus NotificationStatus { get; set; }
    public virtual NotificationType NotyficationType { get; set; }
}

public partial class NotificationStatus
{
    public NotificationStatus()
    {
        this.Notification = new HashSet<Notification>();
    }

    public int Id { get; set; }
    public string Name { get; set; }

    public virtual ICollection<Notification> Notification { get; set; }
}

public partial class NotificationType
{
    public NotificationType()
    {
        this.Notification = new HashSet<Notification>();
    }

    public int Id { get; set; }
    public string Name { get; set; }

    public virtual ICollection<Notification> Notification { get; set; }
}

public partial class Order_Status
{
    public Order_Status()
    {
        this.Contractor_Order = new HashSet<Contractor_Order>();
    }

    public int Id { get; set; }
    public string Name { get; set; }

    public virtual ICollection<Contractor_Order> Contractor_Order { get; set; }
}

public partial class Organization
{
    public Organization()
    {
        this.Standards = new HashSet<Standard>();
    }

    public int Id { get; set; }
    public string Name { get; set; }

    public virtual ICollection<Standard> Standards { get; set; }
}

public partial class Position
{
    public Position()
    {
        this.Users = new HashSet<User>();
    }

    public int Id { get; set; }
    public string Name { get; set; }

    public virtual ICollection<User> Users { get; set; }
}

public partial class Production_material
{
    public Production_material()
    {
        this.Technology = new HashSet<Technology>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string Number { get; set; }
    public string Description { get; set; }
    public int UserId { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int ContractorId { get; set; }

    public virtual ICollection<Technology> Technology { get; set; }
    public virtual User User { get; set; }
    public virtual Contractor Contractor { get; set; }
}

public partial class Production_Order
{
    public int Id { get; set; }
    public string Name { get; set; }
    public int Customer_OrderId { get; set; }
    public string Amount_required { get; set; }

    public virtual Customer_Order Customer_Order { get; set; }
}

public partial class Quality_Chart
{
    public Quality_Chart()
    {
        this.Quality_Chart_Index = new HashSet<Quality_Chart_Index>();
        this.Technology_Stage = new HashSet<Technology_Stage>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int UserId { get; set; }

    public virtual ICollection<Quality_Chart_Index> Quality_Chart_Index { get; set; }
    public virtual User User { get; set; }
    public virtual ICollection<Technology_Stage> Technology_Stage { get; set; }
}

public partial class Quality_Chart_Files
{
    public int Id { get; set; }
    public string File_title { get; set; }
    public string File_name_number { get; set; }
    public string filePath { get; set; }
    public string File_extension { get; set; }
    public Nullable<decimal> File_size { get; set; }
    public string Description { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int UserId { get; set; }
    public int Quality_Chart_IndexId { get; set; }

    public virtual User User { get; set; }
    public virtual Quality_Chart_Index Quality_Chart_Index { get; set; }
}

public partial class Quality_Chart_Index
{
    public Quality_Chart_Index()
    {
        this.Quality_Chart_Files = new HashSet<Quality_Chart_Files>();
    }

    public int Id { get; set; }
    public int Index_number { get; set; }
    public string Index_description { get; set; }
    public int Quality_ChartId { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public string Date_approved { get; set; }
    public int UserId { get; set; }
    public int UserId_approved { get; set; }

    public virtual Quality_Chart Quality_Chart { get; set; }
    public virtual User User { get; set; }
    public virtual User User_approved { get; set; }
    public virtual ICollection<Quality_Chart_Files> Quality_Chart_Files { get; set; }
}

public partial class Quality_Instruction
{
    public Quality_Instruction()
    {
        this.Quality_Instruction_Index = new HashSet<Quality_Instruction_Index>();
        this.Technology_Stage = new HashSet<Technology_Stage>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int UserId { get; set; }

    public virtual User User { get; set; }
    public virtual ICollection<Quality_Instruction_Index> Quality_Instruction_Index { get; set; }
    public virtual ICollection<Technology_Stage> Technology_Stage { get; set; }
}

public partial class Quality_Instruction_Files
{
    public int Id { get; set; }
    public string File_title { get; set; }
    public string File_name_number { get; set; }
    public string filePath { get; set; }
    public string File_extension { get; set; }
    public Nullable<decimal> File_size { get; set; }
    public string Description { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int Quality_Instruction_IndexId { get; set; }
    public int UserId { get; set; }

    public virtual Quality_Instruction_Index Quality_Instruction_Index { get; set; }
    public virtual User User { get; set; }
}

public partial class Quality_Instruction_Index
{
    public Quality_Instruction_Index()
    {
        this.Quality_Instruction_Files = new HashSet<Quality_Instruction_Files>();
    }

    public int Id { get; set; }
    public int Index_number { get; set; }
    public string Index_description { get; set; }
    public int Quality_InstructionId { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int UserId { get; set; }
    public Nullable<int> UserId_approved { get; set; }
    public string Date_approved { get; set; }

    public virtual User User { get; set; }
    public virtual User User_approved { get; set; }
    public virtual Quality_Instruction Quality_Instruction { get; set; }
    public virtual ICollection<Quality_Instruction_Files> Quality_Instruction_Files { get; set; }
}

public partial class QualityDocumentation
{
    public QualityDocumentation()
    {
        this.QualityDocumentation_Files = new HashSet<QualityDocumentation_Files>();
    }

    public int Id { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int QualityDocumentationTypeId { get; set; }

    public virtual QualityDocumentationType QualityDocumentationType { get; set; }
    public virtual ICollection<QualityDocumentation_Files> QualityDocumentation_Files { get; set; }
}

public partial class QualityDocumentation_Files
{
    public int Id { get; set; }
    public string Title { get; set; }
    public string Index { get; set; }
    public string filePath { get; set; }
    public string File_extension { get; set; }
    public Nullable<decimal> File_size { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int QualityDocumentationId { get; set; }

    public virtual QualityDocumentation QualityDocumentation { get; set; }
}

public partial class QualityDocumentationType
{
    public QualityDocumentationType()
    {
        this.QualityDocumentation = new HashSet<QualityDocumentation>();
    }

    public int Id { get; set; }
    public string Name { get; set; }

    public virtual ICollection<QualityDocumentation> QualityDocumentation { get; set; }
}

public partial class Score
{
    public int Id { get; set; }
    public short Delivery_time { get; set; }
    public short Price { get; set; }
    public short Contact { get; set; }
    public string Description { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int UserId { get; set; }
    public short Quality { get; set; }
    public int Contractor_OrderId { get; set; }

    public virtual User User { get; set; }
    public virtual Contractor_Order Contractor_Order { get; set; }
}

public partial class Setup_Sheet
{
    public Setup_Sheet()
    {
        this.Setup_Sheet_Index = new HashSet<Setup_Sheet_Index>();
        this.Technology_Stage = new HashSet<Technology_Stage>();
        this.CNC_Program = new HashSet<CNC_Program>();
        this.CMM_Program = new HashSet<CMM_Program>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int UserId { get; set; }

    public virtual ICollection<Setup_Sheet_Index> Setup_Sheet_Index { get; set; }
    public virtual User User { get; set; }
    public virtual ICollection<Technology_Stage> Technology_Stage { get; set; }
    public virtual ICollection<CNC_Program> CNC_Program { get; set; }
    public virtual ICollection<CMM_Program> CMM_Program { get; set; }
}

public partial class Setup_Sheet_Files
{
    public int Id { get; set; }
    public string File_title { get; set; }
    public string File_name_number { get; set; }
    public string filePath { get; set; }
    public string File_extension { get; set; }
    public Nullable<decimal> File_size { get; set; }
    public string Description { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int Setup_Sheet_IndexId { get; set; }
    public int UserId { get; set; }

    public virtual Setup_Sheet_Index Setup_Sheet_Index { get; set; }
    public virtual User User { get; set; }
}

public partial class Setup_Sheet_Index
{
    public Setup_Sheet_Index()
    {
        this.Setup_Sheet_Files = new HashSet<Setup_Sheet_Files>();
    }

    public int Id { get; set; }
    public int Index_number { get; set; }
    public string Index_description { get; set; }
    public int Setup_SheetId { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int UserId { get; set; }
    public System.DateTime Date_approved { get; set; }
    public int UserId_approved { get; set; }

    public virtual ICollection<Setup_Sheet_Files> Setup_Sheet_Files { get; set; }
    public virtual Setup_Sheet Setup_Sheet { get; set; }
    public virtual User User { get; set; }
    public virtual User User_approved { get; set; }
}

public partial class Standard
{
    public Standard()
    {
        this.Standard_Files = new HashSet<Standard_Files>();
    }

    public int Id { get; set; }
    public string Number { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int OrganizationId { get; set; }

    public virtual Organization Organization { get; set; }
    public virtual ICollection<Standard_Files> Standard_Files { get; set; }
}

public partial class Standard_Files
{
    public int Id { get; set; }
    public string Index { get; set; }
    public string Index_description { get; set; }
    public System.DateTime Index_date { get; set; }
    public string filePath { get; set; }
    public string File_extension { get; set; }
    public Nullable<decimal> File_size { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int StandardId { get; set; }

    public virtual Standard Standard { get; set; }
}

public partial class Task
{
    public Task()
    {
        this.Comment = new HashSet<Comment>();
    }

    public int Id { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public Nullable<System.DateTime> EndDate { get; set; }
    public int UserIdTask { get; set; }
    public int UserId { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public Nullable<int> NotificationId { get; set; }
    public System.DateTime StartDate { get; set; }
    public System.DateTime RequiredEndDate { get; set; }
    public int Priorytet { get; set; }
    public int TaskStatusId { get; set; }

    public virtual User User { get; set; }
    public virtual User User_task { get; set; }
    public virtual Notification Notification { get; set; }
    public virtual ICollection<Comment> Comment { get; set; }
    public virtual TaskStatus TaskStatus { get; set; }
}

public partial class TaskStatus
{
    public TaskStatus()
    {
        this.Task = new HashSet<Task>();
    }

    public int Id { get; set; }
    public string Name { get; set; }

    public virtual ICollection<Task> Task { get; set; }
}

public partial class Technology
{
    public Technology()
    {
        this.Technology_Index = new HashSet<Technology_Index>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int UserId { get; set; }
    public int Customer_Part_IndexId { get; set; }
    public int Production_materialId { get; set; }

    public virtual User User { get; set; }
    public virtual ICollection<Technology_Index> Technology_Index { get; set; }
    public virtual Customer_Part_Index Customer_Part_Index { get; set; }
    public virtual Production_material Production_material { get; set; }
}

public partial class Technology_Changes
{
    public int Id { get; set; }
}

public partial class Technology_Dwg
{
    public Technology_Dwg()
    {
        this.Technology_Dwg_Index = new HashSet<Technology_Dwg_Index>();
        this.Technology_Stage = new HashSet<Technology_Stage>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int UserId { get; set; }

    public virtual ICollection<Technology_Dwg_Index> Technology_Dwg_Index { get; set; }
    public virtual User User { get; set; }
    public virtual ICollection<Technology_Stage> Technology_Stage { get; set; }
}

public partial class Technology_Dwg_Files
{
    public int Id { get; set; }
    public string File_title { get; set; }
    public string File_name_number { get; set; }
    public string filePath { get; set; }
    public string File_extension { get; set; }
    public Nullable<decimal> File_size { get; set; }
    public string Description { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int Technology_Dwg_IndexId { get; set; }
    public int UserId { get; set; }

    public virtual Technology_Dwg_Index Technology_Dwg_Index { get; set; }
    public virtual User User { get; set; }
}

public partial class Technology_Dwg_Index
{
    public Technology_Dwg_Index()
    {
        this.Technology_Dwg_Files = new HashSet<Technology_Dwg_Files>();
    }

    public int Id { get; set; }
    public int Index_number { get; set; }
    public string Index_description { get; set; }
    public int Technology_DwgId { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int UserId { get; set; }
    public System.DateTime Date_approved { get; set; }
    public int UserId_approved { get; set; }

    public virtual Technology_Dwg Technology_Dwg { get; set; }
    public virtual User User { get; set; }
    public virtual User User_approved { get; set; }
    public virtual ICollection<Technology_Dwg_Files> Technology_Dwg_Files { get; set; }
}

public partial class Technology_Files
{
    public int Id { get; set; }
    public string File_title { get; set; }
    public string File_name_number { get; set; }
    public string filePath { get; set; }
    public string File_extension { get; set; }
    public Nullable<decimal> File_size { get; set; }
    public string Description { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int UserId { get; set; }
    public int Technology_Instruction_IndexId { get; set; }

    public virtual User User { get; set; }
    public virtual Technology_Instruction_Index Technology_Instruction_Index { get; set; }
}

public partial class Technology_Index
{
    public Technology_Index()
    {
        this.Technology_Stage = new HashSet<Technology_Stage>();
    }

    public int Id { get; set; }
    public long Index_number { get; set; }
    public string Description { get; set; }
    public int UserId_created { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public Nullable<int> UserId_approced { get; set; }
    public Nullable<System.DateTime> Date_approved { get; set; }
    public int TechnologyId { get; set; }

    public virtual User User { get; set; }
    public virtual User Approved_by { get; set; }
    public virtual Technology Technology { get; set; }
    public virtual ICollection<Technology_Stage> Technology_Stage { get; set; }
}

public partial class Technology_Instruction
{
    public Technology_Instruction()
    {
        this.Technology_Instruction_Indexes = new HashSet<Technology_Instruction_Index>();
        this.Technology_Stage = new HashSet<Technology_Stage>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int UserId { get; set; }

    public virtual ICollection<Technology_Instruction_Index> Technology_Instruction_Indexes { get; set; }
    public virtual User User { get; set; }
    public virtual ICollection<Technology_Stage> Technology_Stage { get; set; }
}

public partial class Technology_Instruction_Index
{
    public Technology_Instruction_Index()
    {
        this.Technology_Files = new HashSet<Technology_Files>();
    }

    public int Id { get; set; }
    public string Index_description { get; set; }
    public int Index_number { get; set; }
    public Nullable<int> Technology_InstructionId { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int UserId { get; set; }
    public System.DateTime Date_approved { get; set; }
    public int UserId_approved { get; set; }

    public virtual Technology_Instruction Technology_Instruction { get; set; }
    public virtual User User { get; set; }
    public virtual User User_approved { get; set; }
    public virtual ICollection<Technology_Files> Technology_Files { get; set; }
}

public partial class Technology_Stage
{
    public Technology_Stage()
    {
        this.Technology_Instruction = new HashSet<Technology_Instruction>();
        this.Technology_Dwg = new HashSet<Technology_Dwg>();
        this.Setup_Sheet = new HashSet<Setup_Sheet>();
        this.CNC_Program = new HashSet<CNC_Program>();
        this.Quality_Instruction = new HashSet<Quality_Instruction>();
        this.Quality_Chart = new HashSet<Quality_Chart>();
        this.CMM_Program = new HashSet<CMM_Program>();
    }

    public int Id { get; set; }
    public int Number { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public int Operation_time { get; set; }
    public int UserId { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int Technology_IndexId { get; set; }

    public virtual User User { get; set; }
    public virtual Technology_Index Technology_Index { get; set; }
    public virtual ICollection<Technology_Instruction> Technology_Instruction { get; set; }
    public virtual ICollection<Technology_Dwg> Technology_Dwg { get; set; }
    public virtual ICollection<Setup_Sheet> Setup_Sheet { get; set; }
    public virtual ICollection<CNC_Program> CNC_Program { get; set; }
    public virtual ICollection<Quality_Instruction> Quality_Instruction { get; set; }
    public virtual ICollection<Quality_Chart> Quality_Chart { get; set; }
    public virtual ICollection<CMM_Program> CMM_Program { get; set; }
}

public partial class Tool
{
    public Tool()
    {
        this.Tool_Document_File = new HashSet<Tool_Document_File>();
        this.Tool_Element = new HashSet<Tool_Element>();
        this.ToolCNC_Program = new HashSet<ToolCNC_Program>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int UserId { get; set; }
    public string Tool_Number { get; set; }
    public int Tool_Assembly_TypeId { get; set; }
    public int Tool_Holder_SystemId { get; set; }

    public virtual ICollection<Tool_Document_File> Tool_Document_File { get; set; }
    public virtual User User { get; set; }
    public virtual ICollection<Tool_Element> Tool_Element { get; set; }
    public virtual ICollection<ToolCNC_Program> ToolCNC_Program { get; set; }
    public virtual Tool_Assembly_Type Tool_Assembly_Type { get; set; }
    public virtual Tool_Holder_System Tool_Holder_System { get; set; }
}

public partial class Tool_Assembly_Type
{
    public Tool_Assembly_Type()
    {
        this.Tool = new HashSet<Tool>();
    }

    public int Id { get; set; }
    public string Name { get; set; }

    public virtual ICollection<Tool> Tool { get; set; }
}

public partial class Tool_Document_File
{
    public int Id { get; set; }
    public string File_title { get; set; }
    public string Description { get; set; }
    public string filePath { get; set; }
    public string File_extension { get; set; }
    public Nullable<decimal> File_size { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public int Tool_Document_TypeId { get; set; }
    public Nullable<int> ToolId { get; set; }
    public Nullable<int> Tool_ElementId { get; set; }
    public string File_name_number { get; set; }
    public int UserId { get; set; }

    public virtual Tool_Document_Type Tool_Document_Type { get; set; }
    public virtual Tool Tool { get; set; }
    public virtual Tool_Element Tool_Element { get; set; }
    public virtual User User { get; set; }
}

public partial class Tool_Document_Type
{
    public Tool_Document_Type()
    {
        this.Tool_Document_File = new HashSet<Tool_Document_File>();
    }

    public int Id { get; set; }
    public string Name { get; set; }

    public virtual ICollection<Tool_Document_File> Tool_Document_File { get; set; }
}

public partial class Tool_Element
{
    public Tool_Element()
    {
        this.Tool_Document_File = new HashSet<Tool_Document_File>();
        this.Tool = new HashSet<Tool>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public string Description { get; set; }
    public int ContractorId { get; set; }
    public int Tool_TypeId { get; set; }
    public string Catalog_number { get; set; }
    public int UserId { get; set; }

    public virtual ICollection<Tool_Document_File> Tool_Document_File { get; set; }
    public virtual Contractor Contractor { get; set; }
    public virtual Tool_Type Tool_Type { get; set; }
    public virtual User User { get; set; }
    public virtual ICollection<Tool> Tool { get; set; }
}

public partial class Tool_Holder_System
{
    public Tool_Holder_System()
    {
        this.CNC_Machine = new HashSet<CNC_Machine>();
        this.Tool = new HashSet<Tool>();
    }

    public int Id { get; set; }
    public string Name { get; set; }

    public virtual ICollection<CNC_Machine> CNC_Machine { get; set; }
    public virtual ICollection<Tool> Tool { get; set; }
}

public partial class Tool_Type
{
    public Tool_Type()
    {
        this.Tool_Element = new HashSet<Tool_Element>();
    }

    public int Id { get; set; }
    public string Name { get; set; }

    public virtual ICollection<Tool_Element> Tool_Element { get; set; }
}

public partial class ToolCNC_Program
{
    public int Id { get; set; }
    public int CNC_ProgramId { get; set; }
    public int ToolId { get; set; }

    public virtual CNC_Program CNC_Program { get; set; }
    public virtual Tool Tool { get; set; }
}

public partial class User
{
    public User()
    {
        this.Notifications = new HashSet<Notification>();
        this.Customers = new HashSet<Customer>();
        this.Customer_Contacts = new HashSet<Customer_Contact>();
        this.Comments = new HashSet<Comment>();
        this.Contractor_Orders = new HashSet<Contractor_Order>();
        this.Contractor_Contacts = new HashSet<Contractor_Contact>();
        this.Contractors = new HashSet<Contractor>();
        this.Scores = new HashSet<Score>();
        this.Customer_Products = new HashSet<Customer_Product>();
        this.Customer_Parts = new HashSet<Customer_Part>();
        this.Customer_Part_Indexes = new HashSet<Customer_Part_Index>();
        this.Customer_Product_Indexex = new HashSet<Customer_Product_Index>();
        this.Customer_Files = new HashSet<Customer_Files>();
        this.Technology = new HashSet<Technology_Index>();
        this.Technology1 = new HashSet<Technology_Index>();
        this.Technology_Stage = new HashSet<Technology_Stage>();
        this.Technology_Dwg = new HashSet<Technology_Dwg>();
        this.Quality_Instruction = new HashSet<Quality_Instruction>();
        this.Quality_Instruction_Index = new HashSet<Quality_Instruction_Index>();
        this.Technology_Dwg_Index = new HashSet<Technology_Dwg_Index>();
        this.Technology_Dwg_Index1 = new HashSet<Technology_Dwg_Index>();
        this.Quality_Instruction_Index1 = new HashSet<Quality_Instruction_Index>();
        this.CNC_Program = new HashSet<CNC_Program_Index>();
        this.Technology_Files = new HashSet<Technology_Files>();
        this.Technology_Instruction_Index = new HashSet<Technology_Instruction_Index>();
        this.Technology_Instruction_Index1 = new HashSet<Technology_Instruction_Index>();
        this.Technology_Instruction = new HashSet<Technology_Instruction>();
        this.CNC_Program2 = new HashSet<CNC_Program>();
        this.Technology2 = new HashSet<Technology>();
        this.Fixture = new HashSet<Fixture>();
        this.CNC_Subprogram_Index = new HashSet<CNC_Subprogram_Index>();
        this.CNC_Subrogram = new HashSet<CNC_Subprogram>();
        this.Change_Request = new HashSet<Change_Request>();
        this.Task = new HashSet<Task>();
        this.Task1 = new HashSet<Task>();
        this.User2 = new HashSet<User>();
        this.DocumentInOut = new HashSet<DocumentInOut>();
        this.DocumentInOut1 = new HashSet<DocumentInOut>();
        this.Technology_Dwg_Files = new HashSet<Technology_Dwg_Files>();
        this.Setup_Sheet_Files = new HashSet<Setup_Sheet_Files>();
        this.Setup_Sheet_Index = new HashSet<Setup_Sheet_Index>();
        this.Setup_Sheet_Index1 = new HashSet<Setup_Sheet_Index>();
        this.Setup_Sheet = new HashSet<Setup_Sheet>();
        this.Quality_Instruction_Files = new HashSet<Quality_Instruction_Files>();
        this.Quality_Chart = new HashSet<Quality_Chart>();
        this.Quality_Chart_Index = new HashSet<Quality_Chart_Index>();
        this.Quality_Chart_Index1 = new HashSet<Quality_Chart_Index>();
        this.Quality_Chart_Files = new HashSet<Quality_Chart_Files>();
        this.Tool = new HashSet<Tool>();
        this.Tool_Element = new HashSet<Tool_Element>();
        this.Tool_Document_File = new HashSet<Tool_Document_File>();
        this.CNC_Program_Index = new HashSet<CNC_Program_Index>();
        this.CNC_Subprogram_Index1 = new HashSet<CNC_Subprogram_Index>();
        this.CNC_Program_Files = new HashSet<CNC_Program_Files>();
        this.CNC_Subprogram_Files = new HashSet<CNC_Subprogram_Files>();
        this.CMM_Program = new HashSet<CMM_Program>();
        this.CMM_Program_Index = new HashSet<CMM_Program_Index>();
        this.CMM_Program_Index1 = new HashSet<CMM_Program_Index>();
        this.CMM_Program_Files = new HashSet<CMM_Program_Files>();
        this.Production_material = new HashSet<Production_material>();
    }

    public int Id { get; set; }
    public string F_Name { get; set; }
    public string L_Name { get; set; }
    public int PositionId { get; set; }
    public int DepartmentId { get; set; }
    public string Email { get; set; }
    public string Password { get; set; }
    public string W_Phone_No { get; set; }
    public string M_Phone_No { get; set; }
    public string Description { get; set; }
    public System.DateTime Date_created_modified { get; set; }
    public Nullable<bool> Customer_List { get; set; }
    public Nullable<bool> Customer_Insert { get; set; }
    public Nullable<bool> Customer_Edit { get; set; }
    public Nullable<bool> Customer_Delete { get; set; }
    public Nullable<bool> Customer_Part_List { get; set; }
    public Nullable<bool> Customer_Part_Insert { get; set; }
    public Nullable<bool> Customer_Part_Edit { get; set; }
    public Nullable<bool> Customer_Part_Delete { get; set; }
    public Nullable<bool> Customer_Order_List { get; set; }
    public Nullable<bool> Customer_Order_Insert { get; set; }
    public Nullable<bool> Customer_Order_Edit { get; set; }
    public Nullable<bool> Customer_Order_Delete { get; set; }
    public Nullable<bool> Contractor_List { get; set; }
    public Nullable<bool> Contractor_Insert { get; set; }
    public Nullable<bool> Contractor_Edit { get; set; }
    public Nullable<bool> Contractor_Delete { get; set; }
    public Nullable<bool> Contractor_Order_List { get; set; }
    public Nullable<bool> Contractor_Order_Insert { get; set; }
    public Nullable<bool> Contractor_Order_Edit { get; set; }
    public Nullable<bool> Contractor_Order_Delete { get; set; }
    public Nullable<bool> Notification_List { get; set; }
    public Nullable<bool> Notification_Insert { get; set; }
    public Nullable<bool> Notification_Edit { get; set; }
    public Nullable<bool> Notification_Delete { get; set; }
    public Nullable<bool> Task_List { get; set; }
    public Nullable<bool> Task_Insert { get; set; }
    public Nullable<bool> Task_Edit { get; set; }
    public Nullable<bool> Task_Delete { get; set; }
    public Nullable<bool> Technology_List { get; set; }
    public Nullable<bool> Technology_Insert { get; set; }
    public Nullable<bool> Technology_Edit { get; set; }
    public Nullable<bool> Technology_Delete { get; set; }
    public Nullable<bool> CNC_Program_List { get; set; }
    public Nullable<bool> CNC_Program_Insert { get; set; }
    public Nullable<bool> CNC_Program_Edit { get; set; }
    public Nullable<bool> CNC_Program_Delete { get; set; }
    public Nullable<bool> Tool_List { get; set; }
    public Nullable<bool> Tool_Insert { get; set; }
    public Nullable<bool> Tool_Edit { get; set; }
    public Nullable<bool> Tool_Delete { get; set; }
    public Nullable<bool> Fixture_List { get; set; }
    public Nullable<bool> Fixture_Insert { get; set; }
    public Nullable<bool> Fixture_Edit { get; set; }
    public Nullable<bool> Fixture_Delete { get; set; }
    public Nullable<bool> Quality_List { get; set; }
    public Nullable<bool> Quality_Insert { get; set; }
    public Nullable<bool> Quality_Edit { get; set; }
    public Nullable<bool> Quality_Delete { get; set; }
    public Nullable<bool> CMM_Program_List { get; set; }
    public Nullable<bool> CMM_Program_Insert { get; set; }
    public Nullable<bool> CMM_Program_Edit { get; set; }
    public Nullable<bool> CMM_Program_Delete { get; set; }
    public Nullable<bool> Users_List { get; set; }
    public Nullable<bool> Users_Insert { get; set; }
    public Nullable<bool> Users_Edit { get; set; }
    public Nullable<bool> Users_Delete { get; set; }
    public Nullable<bool> FormTemplates_List { get; set; }
    public Nullable<bool> FormTemplates_Insert { get; set; }
    public Nullable<bool> FormTemplates_Edit { get; set; }
    public Nullable<bool> FormTemplates_Delete { get; set; }
    public Nullable<bool> Admin { get; set; }
    public int UserId { get; set; }

    public virtual Position Position { get; set; }
    public virtual Department Department { get; set; }
    public virtual ICollection<Notification> Notifications { get; set; }
    public virtual ICollection<Customer> Customers { get; set; }
    public virtual ICollection<Customer_Contact> Customer_Contacts { get; set; }
    public virtual ICollection<Comment> Comments { get; set; }
    public virtual ICollection<Contractor_Order> Contractor_Orders { get; set; }
    public virtual ICollection<Contractor_Contact> Contractor_Contacts { get; set; }
    public virtual ICollection<Contractor> Contractors { get; set; }
    public virtual ICollection<Score> Scores { get; set; }
    public virtual ICollection<Customer_Product> Customer_Products { get; set; }
    public virtual ICollection<Customer_Part> Customer_Parts { get; set; }
    public virtual ICollection<Customer_Part_Index> Customer_Part_Indexes { get; set; }
    public virtual ICollection<Customer_Product_Index> Customer_Product_Indexex { get; set; }
    public virtual ICollection<Customer_Files> Customer_Files { get; set; }
    public virtual ICollection<Technology_Index> Technology { get; set; }
    public virtual ICollection<Technology_Index> Technology1 { get; set; }
    public virtual ICollection<Technology_Stage> Technology_Stage { get; set; }
    public virtual ICollection<Technology_Dwg> Technology_Dwg { get; set; }
    public virtual ICollection<Quality_Instruction> Quality_Instruction { get; set; }
    public virtual ICollection<Quality_Instruction_Index> Quality_Instruction_Index { get; set; }
    public virtual ICollection<Technology_Dwg_Index> Technology_Dwg_Index { get; set; }
    public virtual ICollection<Technology_Dwg_Index> Technology_Dwg_Index1 { get; set; }
    public virtual ICollection<Quality_Instruction_Index> Quality_Instruction_Index1 { get; set; }
    public virtual ICollection<CNC_Program_Index> CNC_Program { get; set; }
    public virtual ICollection<Technology_Files> Technology_Files { get; set; }
    public virtual ICollection<Technology_Instruction_Index> Technology_Instruction_Index { get; set; }
    public virtual ICollection<Technology_Instruction_Index> Technology_Instruction_Index1 { get; set; }
    public virtual ICollection<Technology_Instruction> Technology_Instruction { get; set; }
    public virtual ICollection<CNC_Program> CNC_Program2 { get; set; }
    public virtual ICollection<Technology> Technology2 { get; set; }
    public virtual ICollection<Fixture> Fixture { get; set; }
    public virtual ICollection<CNC_Subprogram_Index> CNC_Subprogram_Index { get; set; }
    public virtual ICollection<CNC_Subprogram> CNC_Subrogram { get; set; }
    public virtual ICollection<Change_Request> Change_Request { get; set; }
    public virtual ICollection<Task> Task { get; set; }
    public virtual ICollection<Task> Task1 { get; set; }
    public virtual ICollection<User> User2 { get; set; }
    public virtual User User1 { get; set; }
    public virtual ICollection<DocumentInOut> DocumentInOut { get; set; }
    public virtual ICollection<DocumentInOut> DocumentInOut1 { get; set; }
    public virtual ICollection<Technology_Dwg_Files> Technology_Dwg_Files { get; set; }
    public virtual ICollection<Setup_Sheet_Files> Setup_Sheet_Files { get; set; }
    public virtual ICollection<Setup_Sheet_Index> Setup_Sheet_Index { get; set; }
    public virtual ICollection<Setup_Sheet_Index> Setup_Sheet_Index1 { get; set; }
    public virtual ICollection<Setup_Sheet> Setup_Sheet { get; set; }
    public virtual ICollection<Quality_Instruction_Files> Quality_Instruction_Files { get; set; }
    public virtual ICollection<Quality_Chart> Quality_Chart { get; set; }
    public virtual ICollection<Quality_Chart_Index> Quality_Chart_Index { get; set; }
    public virtual ICollection<Quality_Chart_Index> Quality_Chart_Index1 { get; set; }
    public virtual ICollection<Quality_Chart_Files> Quality_Chart_Files { get; set; }
    public virtual ICollection<Tool> Tool { get; set; }
    public virtual ICollection<Tool_Element> Tool_Element { get; set; }
    public virtual ICollection<Tool_Document_File> Tool_Document_File { get; set; }
    public virtual ICollection<CNC_Program_Index> CNC_Program_Index { get; set; }
    public virtual ICollection<CNC_Subprogram_Index> CNC_Subprogram_Index1 { get; set; }
    public virtual ICollection<CNC_Program_Files> CNC_Program_Files { get; set; }
    public virtual ICollection<CNC_Subprogram_Files> CNC_Subprogram_Files { get; set; }
    public virtual ICollection<CMM_Program> CMM_Program { get; set; }
    public virtual ICollection<CMM_Program_Index> CMM_Program_Index { get; set; }
    public virtual ICollection<CMM_Program_Index> CMM_Program_Index1 { get; set; }
    public virtual ICollection<CMM_Program_Files> CMM_Program_Files { get; set; }
    public virtual ICollection<Production_material> Production_material { get; set; }
}
